name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt dependencies
        run: |
          pip install dbt-core dbt-snowflake

      - name: Run dbt debug
        run: dbt debug --project-dir dags/dbt/data_pipelines --profiles-dir dags/dbt/data_pipelines

      - name: Run dbt models
        run: dbt run --project-dir dags/dbt/data_pipelines --profiles-dir dags/dbt/data_pipelines
